import { describe, expect, it } from "vitest";
import {
  PRODUCTION_FULL_UNIT_SELECTOR_MARGIN_PIXELS,
  PRODUCTION_FULL_UNIT_SELECTOR_OBJECT_HEIGHT_PIXELS,
  PRODUCTION_FULL_UNIT_SELECTOR_OBJECT_WIDTH_PIXELS,
  PRODUCTION_FULL_UNIT_SELECTOR_SIDE_SIZE_PIXELS,
  PRODUCTION_FULL_UNIT_SELECTOR_TOP_HEIGHT_PIXELS,
} from "../src/ui/ProductionFullUnitSelector";

describe("production full unit selector", () => {
  it("ports the frame and grid layout dimensions", () => {
    expect(PRODUCTION_FULL_UNIT_SELECTOR_MARGIN_PIXELS).toBe(2);
    expect(PRODUCTION_FULL_UNIT_SELECTOR_TOP_HEIGHT_PIXELS).toBe(20);
    expect(PRODUCTION_FULL_UNIT_SELECTOR_SIDE_SIZE_PIXELS).toBe(4);
    expect(PRODUCTION_FULL_UNIT_SELECTOR_OBJECT_WIDTH_PIXELS).toBe(45);
    expect(PRODUCTION_FULL_UNIT_SELECTOR_OBJECT_HEIGHT_PIXELS).toBe(51);
  });
});
